author: attrib
name: RepairRecipe
description: Repair your items with the item you need to craft and keep enchantments.
website: http://dev.bukkit.org/server-mods/repairrecipe/
main: de.funkyclan.mc.RepairRecipe.RepairRecipe
version: 0.3-beta
softdepend: [Vault]

permissions:
    RepairRecipe.repair:
        description: Allow users to repair items
        default: true
    RepairRecipe.repair.enchant:
        description: Allow users to repair enchanted items
        default: true
    RepairRecipe.repair.overRepair:
        description: Allow users to over repair items
        default: false